### ISSUE TITLE
Out of the box ./gradew test not working

### ISSUE THREAD

**Issue by russmiles** [microserviceux/muon-java#22]
If you simply grab the code and then run ./gradlew test, the tests fail with: 

io.muoncore.extension.amqp.discovery.externalbroker.FullStackSpec > full amqp based stack works                                                                FAILED
    java.lang.NullPointerException at FullStackSpec.groovy:70

5 tests completed, 1 failed

Investigating reason why.

**Comment by russmiles** [comment]
Not fixed yet.

**Comment by daviddawson** [comment]
This is caused by a lack of an external rabbit broker.
